---

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: restart nginx

- name: Copy default
  template:
    src: default
    dest: /etc/nginx/sites-available
    mode: "u=rw,g=r,o=r"
  notify: restart nginx
