---
resources:
- name: devops-infra
  type: git
  source:
    uri: https://github.com/dimapod/devops-demo.git

- name: devops-code
  type: git
  source:
    uri: https://github.com/dimapod/devops-demo.git
    paths: ["infra/golden-image/base-image"]

- name: base-image-id
  type: s3
  source:
    bucket: dpo-devops
    region_name: eu-central-1
    versioned_file: base-image-id
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:
- name: base-image
  public: true
  serial: true
  plan:
  - get: devops-infra
  - get: devops-code
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: xebiafrance/packer-ansible
          tag: '1.9.4'
      inputs:
        - name: devops-infra
        - name: devops-code
      outputs:
        - name: output
      run:
        path: devops-infra/infra/concourse/pipeline/golden-image/play-packer.sh
    params:
      AWS_ACCESS_KEY_ID: {{s3-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{s3-secret-access-key}}
  - put: base-image-id
    params:
      {file: output/base-image-id}



