---
- name: Install docker
  become: yes
  yum:
    name: docker
    state: present
    update_cache: yes
  notify: restart docker

- name: Add the ec2-user to the docker group
  become: yes
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Create docker user
  become: yes
  user:
    name: docker
    groups: docker

- name: pip docker-py
  become: yes
  pip:
    name: docker-py
    version: 1.10.6
  notify: restart docker

- name: pip docker-compose
  become: yes
  pip:
    name: docker-compose
    version: "{{docker_compose_version}}"
  notify: restart docker

- meta: flush_handlers