---
resources:
- name: devops-infra
  type: git
  source:
    uri: https://github.com/dimapod/devops-demo.git

- name: application-image-s3
  type: s3
  source:
    bucket: dpo-devops
    region_name: eu-central-1
    versioned_file: application-image-id
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}

- name: infra-description-s3
  type: s3
  source:
    bucket: dpo-devops
    region_name: eu-central-1
    versioned_file: terraform.tfstate
    access_key_id: {{access-key-id}}
    secret_access_key: {{secret-access-key}}

jobs:
- name: infra-destroy-plan
  public: true
  serial: true
  serial_groups: ["infra"]
  plan:
  - get: devops-infra
  - get: application-image-s3
  - get: infra-description-s3

  - task: plan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: uzyexe/terraform
      inputs:
        - name: devops-infra
        - name: application-image-s3
        - name: infra-description-s3
      outputs:
        - name: infra-description
      run:
        path: devops-infra/infra/concourse/pipeline/destroy-infra/task_stop_infra.sh
        args: ["plan"]
    params:
      AWS_ACCESS_KEY_ID: {{access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{secret-access-key}}

- name: infra-destroy
  public: true
  serial: true
  serial_groups: ["infra"]
  plan:
  - get: devops-infra
  - get: application-image-s3
  - get: infra-description-s3
    passed: [infra-destroy-plan]

  - task: destroy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: uzyexe/terraform
      inputs:
        - name: devops-infra
        - name: application-image-s3
        - name: infra-description-s3
      outputs:
        - name: infra-description
      run:
        path: devops-infra/infra/concourse/pipeline/destroy-infra/task_stop_infra.sh
        args: ["destroy"]
    params:
      AWS_ACCESS_KEY_ID: {{access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{secret-access-key}}

  - put: infra-description-s3
    params:
      {file: infra-description/terraform.tfstate}
