---
#resource_types:
#- name: packer
#  type: docker-image
#  source:
#    repository: jdub/packer-resource


resources:
- name: resource-app
  type: git
  source:
    uri: https://github.com/dimapod/devops-demo.git


jobs:
- name: job-test-app
  public: true
  serial: true
  plan:
  - get: resource-app
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: xebiafrance/packer-ansible
          tag: '1.9.0'
      inputs:
        - name: resource-app
      run:
        path: resource-app/concourse/pipeline/golden-image/play-packer.sh
    params:
      AWS_ACCESS_KEY_ID: {{s3-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{s3-secret-access-key}}


