---
resources:
- name: resource-app
  type: git
  source:
    uri: https://github.com/dimapod/devops-demo.git

- name: golden-ami-s3
  type: s3
  source:
    bucket: dpo-devops
    region_name: eu-central-1
    versioned_file: base-golden-ami-(.*).txt
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:
- name: build-golden-image
  public: true
  serial: true
  plan:
  - get: resource-app
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: xebiafrance/packer-ansible
          tag: '1.9.4'
      inputs:
        - name: resource-app
      outputs:
        - name: output
      run:
        path: resource-app/concourse/pipeline/golden-image/play-packer.sh
    params:
      AWS_ACCESS_KEY_ID: {{s3-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{s3-secret-access-key}}
  - put: golden-ami-s3
    params:
      {file: output/base-golden-ami-*.txt}



