---
- name: Copy prometheus files
  copy:
    src: "{{ item }}"
    dest: /home/ec2-user
  with_items:
     - docker-compose.yml
     - config.monitoring
     - alertmanager
     - prometheus
  notify: Restart prometheus

- name: Configure prometheus
  template: src=prometheus.yml dest=/home/ec2-user/prometheus
  notify: Restart prometheus
