---
resources:
- name: devops-infra
  type: git
  source:
    uri: https://github.com/dimapod/devops-demo.git

- name: application-ip-s3
  type: s3
  source:
    bucket: dpo-devops
    region_name: eu-central-1
    versioned_file: application-ip
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: infra-state-monitoring-s3
  type: s3
  source:
    bucket: dpo-devops
    region_name: eu-central-1
    versioned_file: terraform-monitoring.tfstate
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: monitoring-ip-s3
  type: s3
  source:
    bucket: dpo-devops
    region_name: eu-central-1
    versioned_file: monitoring-ip
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:

# Infrastructure apply
- name: infra-apply
  serial: true
  public: true
  serial_groups: ["prometheus"]
  plan:
  - get: devops-infra
  - get: application-ip-s3

  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: uzyexe/terraform
      inputs:
        - name: devops-infra
        - name: application-ip-s3
      outputs:
        - name: infra-description
      run:
        path: devops-infra/infra/concourse/pipeline/monitoring/monitoring_deploy.sh
        args: ["apply"]
    params:
      AWS_ACCESS_KEY_ID: {{s3-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{s3-secret-access-key}}

  - put: infra-state-monitoring-s3
    params:
      file: infra-description/terraform-monitoring.tfstate
  - put: monitoring-ip-s3
    params:
      file: infra-description/monitoring-ip
      acl: public-read
