
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "dpodyachiy_frankfurt"

    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.terminate_on_shutdown = false

    aws.instance_type = "t2.micro"
    aws.region = "eu-central-1"
    aws.ami = "ami-f9619996"

    aws.tags = {
      'Name' => 'DPO Concourse'
    }

    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "~/dpodyachiy_frankfurt.pem"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = 'v'
    ansible.playbook = "site.yml"

  end
end